### ISSUE TITLE
Please add IP address in log_sessions table for adlu-proxy

### ISSUE THREAD

**Issue by thomasberglund** [clickonetwo/adobe-device-licensing-utilities#13]
If possible, it would be helpful to also have the IP address in the log_sessions table for adlu-proxy.

Can this also be added to an existing database?

**Comment by brotskydotcom2** [comment]
> Can this also be added to an existing database?

Yes, the existing database can be altered to add the new field, but of course that value will be empty for all existing records.  I will try to make the database alternation part of startup, so that the new version can be run on an older database without a special upgrade step.

**Comment by thomasberglund** [comment]
Sounds good. Thanks!

**Comment by brotskydotcom2** [comment]
This change will require propagating the client IP through all the request handling, so it needs to be done as part of the request remodeling that is the main work of 1.2.
